apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fineract-dev

resources:
  - ../../base

# Use labels instead of commonLabels to avoid affecting Service selectors
labels:
  - pairs:
      environment: dev
      deployment-type: aws
      managed-by: argocd
    includeSelectors: false

# Override hostname configuration for dev environment
configMapGenerator:
  - name: ingress-config
    behavior: merge
    literals:
      - auth-hostname=a0f502727535147dfa54da5ebf550259-5f54df3f4ec2ce5c.elb.eu-central-1.amazonaws.com

patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --hostname=a0f502727535147dfa54da5ebf550259-5f54df3f4ec2ce5c.elb.eu-central-1.amazonaws.com
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --hostname-backchannel-dynamic=true
    target:
      kind: Deployment
      name: keycloak
  # Fix service selector to match pod labels (override commonLabels)
  - patch: |-
      apiVersion: v1
      kind: Service
      metadata:
        name: keycloak-service
      spec:
        selector:
          app: keycloak
    target:
      kind: Service
      name: keycloak-service
