apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - nginx-configmap.yaml

commonLabels:
  app.kubernetes.io/name: branch-manager-app
  app.kubernetes.io/component: frontend
  app.kubernetes.io/managed-by: kustomize

images:
  - name: ghcr.io/adorsys-gis/fineract-apps/branch-manager-app
    newTag: dc9ade2