apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fineract-uat

# Base configuration
resources:
- ../../base

# Environment-specific ConfigMap for variables
configMapGenerator:
- name: keycloak-config-vars
  literals:
  - domain=uat.fineract.com
  - auth-hostname=auth.uat.fineract.com
  - apps-hostname=apps.uat.fineract.com
  - smtp-host=email-smtp.us-east-2.amazonaws.com
  - smtp-port=587

# Labels for uat environment
labels:
- pairs:
    environment: uat
