apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - serviceaccount.yaml
  - networkpolicy.yaml
  - pdb.yaml
  - hpa.yaml

commonLabels:
  app.kubernetes.io/name: asset-service
  app.kubernetes.io/component: backend
  app.kubernetes.io/part-of: self-service
  app.kubernetes.io/managed-by: kustomize

images:
  - name: ghcr.io/adorsys-gis/fineract-apps/asset-service
    newTag: latest
