apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace managed by environment overlay
# namespace field removed - will be set in environments/*/kustomization.yaml

resources:
  - create-databases-job.yaml
  - fineract-schema-migration-job.yaml

# Image version management
# Allows overriding image tags per environment
images:
  # PostgreSQL client for database initialization
  - name: postgres
    newTag: "15-alpine"

  # Fineract for schema migration
  - name: apache/fineract
    newTag: "develop"

commonLabels:
  app.kubernetes.io/part-of: fineract-database-init
  app.kubernetes.io/managed-by: kustomize
