apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace managed by environment overlay - removed from base
# namespace field will be set by ArgoCD Application

resources:
  - create-keycloak-db-job.yaml

# Image version management
# Allows overriding postgres image tag per environment
images:
  - name: postgres
    newTag: "15-alpine"

commonLabels:
  app.kubernetes.io/name: database-setup
  app.kubernetes.io/part-of: fineract-platform
  app.kubernetes.io/component: database
