apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-config
  namespace: fineract-dev
data:
  apps-hostname: ae0908c81fc014f27947457211ddd1e2-b404da3223ba7b33.elb.eu-central-1.amazonaws.com
  auth-hostname: ae0908c81fc014f27947457211ddd1e2-b404da3223ba7b33.elb.eu-central-1.amazonaws.com
  cluster-issuer: selfsigned-issuer
  auth-signin-url: https://ae0908c81fc014f27947457211ddd1e2-b404da3223ba7b33.elb.eu-central-1.amazonaws.com/oauth2/start?rd=$escaped_request_uri
  cors-allow-origin-url: https://ae0908c81fc014f27947457211ddd1e2-b404da3223ba7b33.elb.eu-central-1.amazonaws.com
  auth-url: http://oauth2-proxy.fineract-dev.svc.cluster.local:4180/oauth2/auth
