apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-config
  namespace: fineract-dev
data:
  apps-hostname: acac3d6571ca54f90b686aae3e174afc-7c0eaa4aa1c0e3a6.elb.eu-central-1.amazonaws.com
  auth-hostname: acac3d6571ca54f90b686aae3e174afc-7c0eaa4aa1c0e3a6.elb.eu-central-1.amazonaws.com
  cluster-issuer: selfsigned-issuer
