apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-config
  namespace: fineract-dev
data:
  apps-hostname: a09fd8b4f6fab4df19cd17091ab83d47-25a66d99d771040f.elb.eu-central-1.amazonaws.com
  auth-hostname: a09fd8b4f6fab4df19cd17091ab83d47-25a66d99d771040f.elb.eu-central-1.amazonaws.com
  cluster-issuer: selfsigned-issuer
  auth-signin-url: https://a09fd8b4f6fab4df19cd17091ab83d47-25a66d99d771040f.elb.eu-central-1.amazonaws.com/oauth2/start?rd=$escaped_request_uri
  cors-allow-origin-url: https://a09fd8b4f6fab4df19cd17091ab83d47-25a66d99d771040f.elb.eu-central-1.amazonaws.com
  auth-url: http://oauth2-proxy.fineract-dev.svc.cluster.local:4180/oauth2/auth
