apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-config
  namespace: fineract-dev
data:
  apps-hostname: a93dad50ee40140ecaf3b30ef5fbe846-6f21cce7d1f3db4c.elb.eu-central-1.amazonaws.com
  auth-hostname: a93dad50ee40140ecaf3b30ef5fbe846-6f21cce7d1f3db4c.elb.eu-central-1.amazonaws.com
  cluster-issuer: selfsigned-issuer
  auth-signin-url: https://a93dad50ee40140ecaf3b30ef5fbe846-6f21cce7d1f3db4c.elb.eu-central-1.amazonaws.com/oauth2/start?rd=$escaped_request_uri
  cors-allow-origin-url: https://a93dad50ee40140ecaf3b30ef5fbe846-6f21cce7d1f3db4c.elb.eu-central-1.amazonaws.com
  auth-url: http://oauth2-proxy.fineract-dev.svc.cluster.local:4180/oauth2/auth
