apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-config
  namespace: fineract-dev
data:
  # AWS ELB hostname - used for all ingress routing
  # IMPORTANT: This hostname MUST match the actual load balancer hostname
  # Update this value after deploying ingress-nginx if the LB hostname changes
  apps-hostname: ad0560af9570d4048b94f357e584115c-02399aa6a55e8f68.elb.eu-central-1.amazonaws.com
  auth-hostname: ad0560af9570d4048b94f357e584115c-02399aa6a55e8f68.elb.eu-central-1.amazonaws.com
  cluster-issuer: selfsigned-issuer
  auth-signin-url: https://ad0560af9570d4048b94f357e584115c-02399aa6a55e8f68.elb.eu-central-1.amazonaws.com/oauth2/start?rd=$escaped_request_uri
  cors-allow-origin-url: https://ad0560af9570d4048b94f357e584115c-02399aa6a55e8f68.elb.eu-central-1.amazonaws.com
  auth-url: http://oauth2-proxy.fineract-dev.svc.cluster.local:4180/oauth2/auth
