apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-config
  namespace: fineract-dev
data:
  apps-hostname: a93dad50ee40140ecaf3b30ef5fbe846-6f21cce7d1f3db4c.elb.eu-central-1.amazonaws.com
  auth-hostname: a93dad50ee40140ecaf3b30ef5fbe846-6f21cce7d1f3db4c.elb.eu-central-1.amazonaws.com
  cluster-issuer: selfsigned-issuer
