apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-config
  namespace: fineract-dev
data:
  apps-hostname: ae236f3783cac47928b7559158f6f5c4-5941149f506864a2.elb.eu-central-1.amazonaws.com
  auth-hostname: ae236f3783cac47928b7559158f6f5c4-5941149f506864a2.elb.eu-central-1.amazonaws.com
  cluster-issuer: selfsigned-issuer
  auth-signin-url: https://ae236f3783cac47928b7559158f6f5c4-5941149f506864a2.elb.eu-central-1.amazonaws.com/oauth2/start?rd=$escaped_request_uri
  cors-allow-origin-url: https://ae236f3783cac47928b7559158f6f5c4-5941149f506864a2.elb.eu-central-1.amazonaws.com
  auth-url: http://oauth2-proxy.fineract-dev.svc.cluster.local:4180/oauth2/auth
