apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-config
  namespace: fineract-dev
data:
  apps-hostname: a248fc3d904694d09b61c2bbdb848eb9-a61d9dde0b2567a1.elb.us-east-2.amazonaws.com
  auth-hostname: a248fc3d904694d09b61c2bbdb848eb9-a61d9dde0b2567a1.elb.us-east-2.amazonaws.com
  cluster-issuer: selfsigned-issuer
