apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-config
  namespace: fineract-dev
data:
  apps-hostname: a0f502727535147dfa54da5ebf550259-5f54df3f4ec2ce5c.elb.eu-central-1.amazonaws.com
  auth-hostname: a0f502727535147dfa54da5ebf550259-5f54df3f4ec2ce5c.elb.eu-central-1.amazonaws.com
  cluster-issuer: selfsigned-issuer
  auth-signin-url: https://a0f502727535147dfa54da5ebf550259-5f54df3f4ec2ce5c.elb.eu-central-1.amazonaws.com/oauth2/start?rd=$escaped_request_uri
  cors-allow-origin-url: https://a0f502727535147dfa54da5ebf550259-5f54df3f4ec2ce5c.elb.eu-central-1.amazonaws.com
  auth-url: http://oauth2-proxy.fineract-dev.svc.cluster.local:4180/oauth2/auth
