apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-config
  namespace: fineract-dev
data:
  apps-hostname: aeda3c27cce0a428baf14f6ac6066092-c69cc6e625704ca9.elb.eu-central-1.amazonaws.com
  auth-hostname: aeda3c27cce0a428baf14f6ac6066092-c69cc6e625704ca9.elb.eu-central-1.amazonaws.com
  cluster-issuer: selfsigned-issuer
  auth-signin-url: https://aeda3c27cce0a428baf14f6ac6066092-c69cc6e625704ca9.elb.eu-central-1.amazonaws.com/oauth2/start?rd=$escaped_request_uri
  cors-allow-origin-url: https://aeda3c27cce0a428baf14f6ac6066092-c69cc6e625704ca9.elb.eu-central-1.amazonaws.com
  auth-url: http://oauth2-proxy.fineract-dev.svc.cluster.local:4180/oauth2/auth
