apiVersion: v1
kind: ConfigMap
metadata:
  name: fineract-oauth2-config
data:
  # Production environment OAuth2/OIDC configuration
  oidc-issuer-url: "https://auth.fineract.com/realms/fineract"
  jwk-set-uri-internal: "http://keycloak-service:8080/realms/fineract/protocol/openid-connect/certs"
