apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fineract

resources:
  - smoke-test-job.yaml
  - configmap.yaml

commonLabels:
  app.kubernetes.io/name: smoke-tests
  app.kubernetes.io/component: testing
  app.kubernetes.io/managed-by: kustomize
