apiVersion: v1
kind: ConfigMap
metadata:
  name: fineract-oauth2-config
data:
  # Development environment OAuth2/OIDC configuration
  oidc-issuer-url: "https://a248fc3d904694d09b61c2bbdb848eb9-a61d9dde0b2567a1.elb.us-east-2.amazonaws.com/auth/realms/fineract"
  jwk-set-uri-internal: "http://keycloak-service:8080/auth/realms/fineract/protocol/openid-connect/certs"
